services:
  - type: web
    name: sms-web-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.app:app"
    envVars:
      - key: FLASK_ENV
        value: production
