services:
  - type: web
    name: sms-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
    disk:
      name: data-disk
      mountPath: /data
      sizeGB: 1
